markdown: redcarpet
name: 18F Volunteering Working Group
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go

permalink: pretty
highlighter: rouge

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Main repository
  url: https://github.com/18F/wg-volunteer/
  internal: false
- text: .about.yml
  url: https://github.com/18F/wg-volunteer/blob/18f-pages/.about.yml
  internal: false
- text: Team Notes
  url: https://docs.google.com/document/d/1UnlUMCREwfYcAeJRyuMhmFruLwaJQ8v8eMtGPtKVB04/edit#
  internal: false


repos:
- name: 18F Volunteering Working Group
  description: Main repository
  url: https://github.com/18F/wg-volunteer

back_link:
  url: "https://pages.18f.gov/"
  text: Read more 18F Pages

google_analytics_ua: UA-48605964-19

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
